services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Application\Helpers\Slug\SlugGenerator:
        class: Application\Helpers\Slug\SlugGenerator

    Application\Helpers\EventListeners\MigrationEventListener:
        tags:
            - { name: doctrine.event_listener, event: 'postGenerateSchema' }
